// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.2
// source: auth/auth.proto

package auth

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request messages
type CheckPhoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"` // Language preference
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPhoneRequest) Reset() {
	*x = CheckPhoneRequest{}
	mi := &file_auth_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPhoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPhoneRequest) ProtoMessage() {}

func (x *CheckPhoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPhoneRequest.ProtoReflect.Descriptor instead.
func (*CheckPhoneRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{0}
}

func (x *CheckPhoneRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CheckPhoneRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type LoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_auth_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{1}
}

func (x *LoginRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type SendOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendOTPRequest) Reset() {
	*x = SendOTPRequest{}
	mi := &file_auth_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendOTPRequest) ProtoMessage() {}

func (x *SendOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendOTPRequest.ProtoReflect.Descriptor instead.
func (*SendOTPRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{2}
}

func (x *SendOTPRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SendOTPRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	OtpCode       string                 `protobuf:"bytes,2,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	Lang          string                 `protobuf:"bytes,3,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	mi := &file_auth_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOTPRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *VerifyOTPRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

func (x *VerifyOTPRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_auth_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *RegisterRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type CompleteRegistrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ReferralCode  string                 `protobuf:"bytes,3,opt,name=referral_code,json=referralCode,proto3" json:"referral_code,omitempty"` // optional
	FullName      string                 `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	NickName      string                 `protobuf:"bytes,5,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	BirthPlace    string                 `protobuf:"bytes,6,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	BirthDate     string                 `protobuf:"bytes,7,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,8,opt,name=gender,proto3" json:"gender,omitempty"`
	Religion      string                 `protobuf:"bytes,9,opt,name=religion,proto3" json:"religion,omitempty"`
	Address       string                 `protobuf:"bytes,10,opt,name=address,proto3" json:"address,omitempty"`
	Rt            string                 `protobuf:"bytes,11,opt,name=rt,proto3" json:"rt,omitempty"`
	Rw            string                 `protobuf:"bytes,12,opt,name=rw,proto3" json:"rw,omitempty"`
	Province      string                 `protobuf:"bytes,13,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,14,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,15,opt,name=district,proto3" json:"district,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,16,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	PostalCode    string                 `protobuf:"bytes,17,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Npwp          string                 `protobuf:"bytes,18,opt,name=npwp,proto3" json:"npwp,omitempty"`
	Email         string                 `protobuf:"bytes,19,opt,name=email,proto3" json:"email,omitempty"`
	Occupation    string                 `protobuf:"bytes,20,opt,name=occupation,proto3" json:"occupation,omitempty"`
	FundPurpose   string                 `protobuf:"bytes,21,opt,name=fund_purpose,json=fundPurpose,proto3" json:"fund_purpose,omitempty"`
	FundSource    string                 `protobuf:"bytes,22,opt,name=fund_source,json=fundSource,proto3" json:"fund_source,omitempty"`
	AnnualIncome  string                 `protobuf:"bytes,23,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`
	Lang          string                 `protobuf:"bytes,24,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteRegistrationRequest) Reset() {
	*x = CompleteRegistrationRequest{}
	mi := &file_auth_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteRegistrationRequest) ProtoMessage() {}

func (x *CompleteRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteRegistrationRequest.ProtoReflect.Descriptor instead.
func (*CompleteRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{5}
}

func (x *CompleteRegistrationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetReferralCode() string {
	if x != nil {
		return x.ReferralCode
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetRt() string {
	if x != nil {
		return x.Rt
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetRw() string {
	if x != nil {
		return x.Rw
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetNpwp() string {
	if x != nil {
		return x.Npwp
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetFundPurpose() string {
	if x != nil {
		return x.FundPurpose
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetFundSource() string {
	if x != nil {
		return x.FundSource
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetAnnualIncome() string {
	if x != nil {
		return x.AnnualIncome
	}
	return ""
}

func (x *CompleteRegistrationRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type InitiateActivationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	AccountNo     string                 `protobuf:"bytes,2,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Nik           string                 `protobuf:"bytes,3,opt,name=nik,proto3" json:"nik,omitempty"`
	BirthDate     string                 `protobuf:"bytes,4,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	MotherName    string                 `protobuf:"bytes,5,opt,name=mother_name,json=motherName,proto3" json:"mother_name,omitempty"`
	Lang          string                 `protobuf:"bytes,6,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitiateActivationRequest) Reset() {
	*x = InitiateActivationRequest{}
	mi := &file_auth_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitiateActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitiateActivationRequest) ProtoMessage() {}

func (x *InitiateActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitiateActivationRequest.ProtoReflect.Descriptor instead.
func (*InitiateActivationRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{6}
}

func (x *InitiateActivationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *InitiateActivationRequest) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *InitiateActivationRequest) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *InitiateActivationRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *InitiateActivationRequest) GetMotherName() string {
	if x != nil {
		return x.MotherName
	}
	return ""
}

func (x *InitiateActivationRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type CompleteActivationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	BirthPlace    string                 `protobuf:"bytes,5,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	BirthDate     string                 `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Religion      string                 `protobuf:"bytes,8,opt,name=religion,proto3" json:"religion,omitempty"`
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Rt            string                 `protobuf:"bytes,10,opt,name=rt,proto3" json:"rt,omitempty"`
	Rw            string                 `protobuf:"bytes,11,opt,name=rw,proto3" json:"rw,omitempty"`
	Province      string                 `protobuf:"bytes,12,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,14,opt,name=district,proto3" json:"district,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,15,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	PostalCode    string                 `protobuf:"bytes,16,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Npwp          string                 `protobuf:"bytes,17,opt,name=npwp,proto3" json:"npwp,omitempty"`
	Email         string                 `protobuf:"bytes,18,opt,name=email,proto3" json:"email,omitempty"`
	Occupation    string                 `protobuf:"bytes,19,opt,name=occupation,proto3" json:"occupation,omitempty"`
	FundPurpose   string                 `protobuf:"bytes,20,opt,name=fund_purpose,json=fundPurpose,proto3" json:"fund_purpose,omitempty"`
	FundSource    string                 `protobuf:"bytes,21,opt,name=fund_source,json=fundSource,proto3" json:"fund_source,omitempty"`
	AnnualIncome  string                 `protobuf:"bytes,22,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`
	Lang          string                 `protobuf:"bytes,23,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteActivationRequest) Reset() {
	*x = CompleteActivationRequest{}
	mi := &file_auth_auth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteActivationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActivationRequest) ProtoMessage() {}

func (x *CompleteActivationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteActivationRequest.ProtoReflect.Descriptor instead.
func (*CompleteActivationRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{7}
}

func (x *CompleteActivationRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *CompleteActivationRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *CompleteActivationRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CompleteActivationRequest) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *CompleteActivationRequest) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *CompleteActivationRequest) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *CompleteActivationRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *CompleteActivationRequest) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *CompleteActivationRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CompleteActivationRequest) GetRt() string {
	if x != nil {
		return x.Rt
	}
	return ""
}

func (x *CompleteActivationRequest) GetRw() string {
	if x != nil {
		return x.Rw
	}
	return ""
}

func (x *CompleteActivationRequest) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *CompleteActivationRequest) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *CompleteActivationRequest) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *CompleteActivationRequest) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *CompleteActivationRequest) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *CompleteActivationRequest) GetNpwp() string {
	if x != nil {
		return x.Npwp
	}
	return ""
}

func (x *CompleteActivationRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CompleteActivationRequest) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *CompleteActivationRequest) GetFundPurpose() string {
	if x != nil {
		return x.FundPurpose
	}
	return ""
}

func (x *CompleteActivationRequest) GetFundSource() string {
	if x != nil {
		return x.FundSource
	}
	return ""
}

func (x *CompleteActivationRequest) GetAnnualIncome() string {
	if x != nil {
		return x.AnnualIncome
	}
	return ""
}

func (x *CompleteActivationRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_auth_auth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{8}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	Lang          string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_auth_auth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{9}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *LogoutRequest) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

// Response messages
type CheckPhoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPhoneResponse) Reset() {
	*x = CheckPhoneResponse{}
	mi := &file_auth_auth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPhoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPhoneResponse) ProtoMessage() {}

func (x *CheckPhoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPhoneResponse.ProtoReflect.Descriptor instead.
func (*CheckPhoneResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{10}
}

func (x *CheckPhoneResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CheckPhoneResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CheckPhoneResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Data          *AuthTokens            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_auth_auth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{11}
}

func (x *LoginResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LoginResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LoginResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *LoginResponse) GetData() *AuthTokens {
	if x != nil {
		return x.Data
	}
	return nil
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	Data          *AuthTokens            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_auth_auth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{12}
}

func (x *RefreshTokenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RefreshTokenResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RefreshTokenResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RefreshTokenResponse) GetData() *AuthTokens {
	if x != nil {
		return x.Data
	}
	return nil
}

type StandardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Code          string                 `protobuf:"bytes,3,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StandardResponse) Reset() {
	*x = StandardResponse{}
	mi := &file_auth_auth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StandardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StandardResponse) ProtoMessage() {}

func (x *StandardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StandardResponse.ProtoReflect.Descriptor instead.
func (*StandardResponse) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{13}
}

func (x *StandardResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StandardResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *StandardResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// Data structures
type AuthTokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthTokens) Reset() {
	*x = AuthTokens{}
	mi := &file_auth_auth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthTokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthTokens) ProtoMessage() {}

func (x *AuthTokens) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthTokens.ProtoReflect.Descriptor instead.
func (*AuthTokens) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{14}
}

func (x *AuthTokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AuthTokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

// Database models as proto messages (for internal use)
type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,3,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	AccountNo     string                 `protobuf:"bytes,4,opt,name=account_no,json=accountNo,proto3" json:"account_no,omitempty"`
	Nik           string                 `protobuf:"bytes,5,opt,name=nik,proto3" json:"nik,omitempty"`
	BirthDate     string                 `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	MotherName    string                 `protobuf:"bytes,7,opt,name=mother_name,json=motherName,proto3" json:"mother_name,omitempty"`
	IsActivated   bool                   `protobuf:"varint,8,opt,name=is_activated,json=isActivated,proto3" json:"is_activated,omitempty"`
	IsActive      bool                   `protobuf:"varint,9,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_auth_auth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{15}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *User) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *User) GetAccountNo() string {
	if x != nil {
		return x.AccountNo
	}
	return ""
}

func (x *User) GetNik() string {
	if x != nil {
		return x.Nik
	}
	return ""
}

func (x *User) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *User) GetMotherName() string {
	if x != nil {
		return x.MotherName
	}
	return ""
}

func (x *User) GetIsActivated() bool {
	if x != nil {
		return x.IsActivated
	}
	return false
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

type UserFulfillment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FullName      string                 `protobuf:"bytes,3,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	NickName      string                 `protobuf:"bytes,4,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`
	BirthPlace    string                 `protobuf:"bytes,5,opt,name=birth_place,json=birthPlace,proto3" json:"birth_place,omitempty"`
	BirthDate     string                 `protobuf:"bytes,6,opt,name=birth_date,json=birthDate,proto3" json:"birth_date,omitempty"`
	Gender        string                 `protobuf:"bytes,7,opt,name=gender,proto3" json:"gender,omitempty"`
	Religion      string                 `protobuf:"bytes,8,opt,name=religion,proto3" json:"religion,omitempty"`
	Address       string                 `protobuf:"bytes,9,opt,name=address,proto3" json:"address,omitempty"`
	Rt            string                 `protobuf:"bytes,10,opt,name=rt,proto3" json:"rt,omitempty"`
	Rw            string                 `protobuf:"bytes,11,opt,name=rw,proto3" json:"rw,omitempty"`
	Province      string                 `protobuf:"bytes,12,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,13,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,14,opt,name=district,proto3" json:"district,omitempty"`
	SubDistrict   string                 `protobuf:"bytes,15,opt,name=sub_district,json=subDistrict,proto3" json:"sub_district,omitempty"`
	PostalCode    string                 `protobuf:"bytes,16,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Npwp          string                 `protobuf:"bytes,17,opt,name=npwp,proto3" json:"npwp,omitempty"`
	Email         string                 `protobuf:"bytes,18,opt,name=email,proto3" json:"email,omitempty"`
	Occupation    string                 `protobuf:"bytes,19,opt,name=occupation,proto3" json:"occupation,omitempty"`
	FundPurpose   string                 `protobuf:"bytes,20,opt,name=fund_purpose,json=fundPurpose,proto3" json:"fund_purpose,omitempty"`
	FundSource    string                 `protobuf:"bytes,21,opt,name=fund_source,json=fundSource,proto3" json:"fund_source,omitempty"`
	AnnualIncome  string                 `protobuf:"bytes,22,opt,name=annual_income,json=annualIncome,proto3" json:"annual_income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserFulfillment) Reset() {
	*x = UserFulfillment{}
	mi := &file_auth_auth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserFulfillment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserFulfillment) ProtoMessage() {}

func (x *UserFulfillment) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserFulfillment.ProtoReflect.Descriptor instead.
func (*UserFulfillment) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{16}
}

func (x *UserFulfillment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserFulfillment) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserFulfillment) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *UserFulfillment) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *UserFulfillment) GetBirthPlace() string {
	if x != nil {
		return x.BirthPlace
	}
	return ""
}

func (x *UserFulfillment) GetBirthDate() string {
	if x != nil {
		return x.BirthDate
	}
	return ""
}

func (x *UserFulfillment) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *UserFulfillment) GetReligion() string {
	if x != nil {
		return x.Religion
	}
	return ""
}

func (x *UserFulfillment) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UserFulfillment) GetRt() string {
	if x != nil {
		return x.Rt
	}
	return ""
}

func (x *UserFulfillment) GetRw() string {
	if x != nil {
		return x.Rw
	}
	return ""
}

func (x *UserFulfillment) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *UserFulfillment) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *UserFulfillment) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *UserFulfillment) GetSubDistrict() string {
	if x != nil {
		return x.SubDistrict
	}
	return ""
}

func (x *UserFulfillment) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *UserFulfillment) GetNpwp() string {
	if x != nil {
		return x.Npwp
	}
	return ""
}

func (x *UserFulfillment) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserFulfillment) GetOccupation() string {
	if x != nil {
		return x.Occupation
	}
	return ""
}

func (x *UserFulfillment) GetFundPurpose() string {
	if x != nil {
		return x.FundPurpose
	}
	return ""
}

func (x *UserFulfillment) GetFundSource() string {
	if x != nil {
		return x.FundSource
	}
	return ""
}

func (x *UserFulfillment) GetAnnualIncome() string {
	if x != nil {
		return x.AnnualIncome
	}
	return ""
}

type OtpRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,2,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	OtpCode       string                 `protobuf:"bytes,3,opt,name=otp_code,json=otpCode,proto3" json:"otp_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OtpRequest) Reset() {
	*x = OtpRequest{}
	mi := &file_auth_auth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OtpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OtpRequest) ProtoMessage() {}

func (x *OtpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OtpRequest.ProtoReflect.Descriptor instead.
func (*OtpRequest) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{17}
}

func (x *OtpRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OtpRequest) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *OtpRequest) GetOtpCode() string {
	if x != nil {
		return x.OtpCode
	}
	return ""
}

type RefreshToken struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshToken) Reset() {
	*x = RefreshToken{}
	mi := &file_auth_auth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshToken) ProtoMessage() {}

func (x *RefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_auth_auth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshToken.ProtoReflect.Descriptor instead.
func (*RefreshToken) Descriptor() ([]byte, []int) {
	return file_auth_auth_proto_rawDescGZIP(), []int{18}
}

func (x *RefreshToken) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RefreshToken) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RefreshToken) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_auth_auth_proto protoreflect.FileDescriptor

const file_auth_auth_proto_rawDesc = "" +
	"\n" +
	"\x0fauth/auth.proto\x12\x04auth\"J\n" +
	"\x11CheckPhoneRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"a\n" +
	"\fLoginRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\"G\n" +
	"\x0eSendOTPRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"d\n" +
	"\x10VerifyOTPRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\botp_code\x18\x02 \x01(\tR\aotpCode\x12\x12\n" +
	"\x04lang\x18\x03 \x01(\tR\x04lang\"H\n" +
	"\x0fRegisterRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\xc0\x05\n" +
	"\x1bCompleteRegistrationRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rreferral_code\x18\x03 \x01(\tR\freferralCode\x12\x1b\n" +
	"\tfull_name\x18\x04 \x01(\tR\bfullName\x12\x1b\n" +
	"\tnick_name\x18\x05 \x01(\tR\bnickName\x12\x1f\n" +
	"\vbirth_place\x18\x06 \x01(\tR\n" +
	"birthPlace\x12\x1d\n" +
	"\n" +
	"birth_date\x18\a \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\b \x01(\tR\x06gender\x12\x1a\n" +
	"\breligion\x18\t \x01(\tR\breligion\x12\x18\n" +
	"\aaddress\x18\n" +
	" \x01(\tR\aaddress\x12\x0e\n" +
	"\x02rt\x18\v \x01(\tR\x02rt\x12\x0e\n" +
	"\x02rw\x18\f \x01(\tR\x02rw\x12\x1a\n" +
	"\bprovince\x18\r \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\x0e \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0f \x01(\tR\bdistrict\x12!\n" +
	"\fsub_district\x18\x10 \x01(\tR\vsubDistrict\x12\x1f\n" +
	"\vpostal_code\x18\x11 \x01(\tR\n" +
	"postalCode\x12\x12\n" +
	"\x04npwp\x18\x12 \x01(\tR\x04npwp\x12\x14\n" +
	"\x05email\x18\x13 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"occupation\x18\x14 \x01(\tR\n" +
	"occupation\x12!\n" +
	"\ffund_purpose\x18\x15 \x01(\tR\vfundPurpose\x12\x1f\n" +
	"\vfund_source\x18\x16 \x01(\tR\n" +
	"fundSource\x12#\n" +
	"\rannual_income\x18\x17 \x01(\tR\fannualIncome\x12\x12\n" +
	"\x04lang\x18\x18 \x01(\tR\x04lang\"\xc3\x01\n" +
	"\x19InitiateActivationRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1d\n" +
	"\n" +
	"account_no\x18\x02 \x01(\tR\taccountNo\x12\x10\n" +
	"\x03nik\x18\x03 \x01(\tR\x03nik\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x04 \x01(\tR\tbirthDate\x12\x1f\n" +
	"\vmother_name\x18\x05 \x01(\tR\n" +
	"motherName\x12\x12\n" +
	"\x04lang\x18\x06 \x01(\tR\x04lang\"\x99\x05\n" +
	"\x19CompleteActivationRequest\x12!\n" +
	"\fphone_number\x18\x01 \x01(\tR\vphoneNumber\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1f\n" +
	"\vbirth_place\x18\x05 \x01(\tR\n" +
	"birthPlace\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x1a\n" +
	"\breligion\x18\b \x01(\tR\breligion\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x0e\n" +
	"\x02rt\x18\n" +
	" \x01(\tR\x02rt\x12\x0e\n" +
	"\x02rw\x18\v \x01(\tR\x02rw\x12\x1a\n" +
	"\bprovince\x18\f \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0e \x01(\tR\bdistrict\x12!\n" +
	"\fsub_district\x18\x0f \x01(\tR\vsubDistrict\x12\x1f\n" +
	"\vpostal_code\x18\x10 \x01(\tR\n" +
	"postalCode\x12\x12\n" +
	"\x04npwp\x18\x11 \x01(\tR\x04npwp\x12\x14\n" +
	"\x05email\x18\x12 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"occupation\x18\x13 \x01(\tR\n" +
	"occupation\x12!\n" +
	"\ffund_purpose\x18\x14 \x01(\tR\vfundPurpose\x12\x1f\n" +
	"\vfund_source\x18\x15 \x01(\tR\n" +
	"fundSource\x12#\n" +
	"\rannual_income\x18\x16 \x01(\tR\fannualIncome\x12\x12\n" +
	"\x04lang\x18\x17 \x01(\tR\x04lang\"N\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"H\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\"\\\n" +
	"\x12CheckPhoneResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"}\n" +
	"\rLoginResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.auth.AuthTokensR\x04data\"\x84\x01\n" +
	"\x14RefreshTokenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\x12$\n" +
	"\x04data\x18\x04 \x01(\v2\x10.auth.AuthTokensR\x04data\"Z\n" +
	"\x10StandardResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x12\n" +
	"\x04code\x18\x03 \x01(\tR\x04code\"T\n" +
	"\n" +
	"AuthTokens\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x02 \x01(\tR\frefreshToken\"\x8f\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12#\n" +
	"\rpassword_hash\x18\x03 \x01(\tR\fpasswordHash\x12\x1d\n" +
	"\n" +
	"account_no\x18\x04 \x01(\tR\taccountNo\x12\x10\n" +
	"\x03nik\x18\x05 \x01(\tR\x03nik\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\tR\tbirthDate\x12\x1f\n" +
	"\vmother_name\x18\a \x01(\tR\n" +
	"motherName\x12!\n" +
	"\fis_activated\x18\b \x01(\bR\visActivated\x12\x1b\n" +
	"\tis_active\x18\t \x01(\bR\bisActive\"\xe5\x04\n" +
	"\x0fUserFulfillment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tfull_name\x18\x03 \x01(\tR\bfullName\x12\x1b\n" +
	"\tnick_name\x18\x04 \x01(\tR\bnickName\x12\x1f\n" +
	"\vbirth_place\x18\x05 \x01(\tR\n" +
	"birthPlace\x12\x1d\n" +
	"\n" +
	"birth_date\x18\x06 \x01(\tR\tbirthDate\x12\x16\n" +
	"\x06gender\x18\a \x01(\tR\x06gender\x12\x1a\n" +
	"\breligion\x18\b \x01(\tR\breligion\x12\x18\n" +
	"\aaddress\x18\t \x01(\tR\aaddress\x12\x0e\n" +
	"\x02rt\x18\n" +
	" \x01(\tR\x02rt\x12\x0e\n" +
	"\x02rw\x18\v \x01(\tR\x02rw\x12\x1a\n" +
	"\bprovince\x18\f \x01(\tR\bprovince\x12\x12\n" +
	"\x04city\x18\r \x01(\tR\x04city\x12\x1a\n" +
	"\bdistrict\x18\x0e \x01(\tR\bdistrict\x12!\n" +
	"\fsub_district\x18\x0f \x01(\tR\vsubDistrict\x12\x1f\n" +
	"\vpostal_code\x18\x10 \x01(\tR\n" +
	"postalCode\x12\x12\n" +
	"\x04npwp\x18\x11 \x01(\tR\x04npwp\x12\x14\n" +
	"\x05email\x18\x12 \x01(\tR\x05email\x12\x1e\n" +
	"\n" +
	"occupation\x18\x13 \x01(\tR\n" +
	"occupation\x12!\n" +
	"\ffund_purpose\x18\x14 \x01(\tR\vfundPurpose\x12\x1f\n" +
	"\vfund_source\x18\x15 \x01(\tR\n" +
	"fundSource\x12#\n" +
	"\rannual_income\x18\x16 \x01(\tR\fannualIncome\"Z\n" +
	"\n" +
	"OtpRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fphone_number\x18\x02 \x01(\tR\vphoneNumber\x12\x19\n" +
	"\botp_code\x18\x03 \x01(\tR\aotpCode\"M\n" +
	"\fRefreshToken\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token2\x9d\x05\n" +
	"\vAuthService\x12?\n" +
	"\n" +
	"CheckPhone\x12\x17.auth.CheckPhoneRequest\x1a\x18.auth.CheckPhoneResponse\x120\n" +
	"\x05Login\x12\x12.auth.LoginRequest\x1a\x13.auth.LoginResponse\x127\n" +
	"\aSendOTP\x12\x14.auth.SendOTPRequest\x1a\x16.auth.StandardResponse\x12;\n" +
	"\tVerifyOTP\x12\x16.auth.VerifyOTPRequest\x1a\x16.auth.StandardResponse\x129\n" +
	"\bRegister\x12\x15.auth.RegisterRequest\x1a\x16.auth.StandardResponse\x12N\n" +
	"\x14CompleteRegistration\x12!.auth.CompleteRegistrationRequest\x1a\x13.auth.LoginResponse\x12M\n" +
	"\x12InitiateActivation\x12\x1f.auth.InitiateActivationRequest\x1a\x16.auth.StandardResponse\x12M\n" +
	"\x12CompleteActivation\x12\x1f.auth.CompleteActivationRequest\x1a\x16.auth.StandardResponse\x12E\n" +
	"\fRefreshToken\x12\x19.auth.RefreshTokenRequest\x1a\x1a.auth.RefreshTokenResponse\x125\n" +
	"\x06Logout\x12\x13.auth.LogoutRequest\x1a\x16.auth.StandardResponseB\x19Z\x17auth-service/proto/authb\x06proto3"

var (
	file_auth_auth_proto_rawDescOnce sync.Once
	file_auth_auth_proto_rawDescData []byte
)

func file_auth_auth_proto_rawDescGZIP() []byte {
	file_auth_auth_proto_rawDescOnce.Do(func() {
		file_auth_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)))
	})
	return file_auth_auth_proto_rawDescData
}

var file_auth_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_auth_auth_proto_goTypes = []any{
	(*CheckPhoneRequest)(nil),           // 0: auth.CheckPhoneRequest
	(*LoginRequest)(nil),                // 1: auth.LoginRequest
	(*SendOTPRequest)(nil),              // 2: auth.SendOTPRequest
	(*VerifyOTPRequest)(nil),            // 3: auth.VerifyOTPRequest
	(*RegisterRequest)(nil),             // 4: auth.RegisterRequest
	(*CompleteRegistrationRequest)(nil), // 5: auth.CompleteRegistrationRequest
	(*InitiateActivationRequest)(nil),   // 6: auth.InitiateActivationRequest
	(*CompleteActivationRequest)(nil),   // 7: auth.CompleteActivationRequest
	(*RefreshTokenRequest)(nil),         // 8: auth.RefreshTokenRequest
	(*LogoutRequest)(nil),               // 9: auth.LogoutRequest
	(*CheckPhoneResponse)(nil),          // 10: auth.CheckPhoneResponse
	(*LoginResponse)(nil),               // 11: auth.LoginResponse
	(*RefreshTokenResponse)(nil),        // 12: auth.RefreshTokenResponse
	(*StandardResponse)(nil),            // 13: auth.StandardResponse
	(*AuthTokens)(nil),                  // 14: auth.AuthTokens
	(*User)(nil),                        // 15: auth.User
	(*UserFulfillment)(nil),             // 16: auth.UserFulfillment
	(*OtpRequest)(nil),                  // 17: auth.OtpRequest
	(*RefreshToken)(nil),                // 18: auth.RefreshToken
}
var file_auth_auth_proto_depIdxs = []int32{
	14, // 0: auth.LoginResponse.data:type_name -> auth.AuthTokens
	14, // 1: auth.RefreshTokenResponse.data:type_name -> auth.AuthTokens
	0,  // 2: auth.AuthService.CheckPhone:input_type -> auth.CheckPhoneRequest
	1,  // 3: auth.AuthService.Login:input_type -> auth.LoginRequest
	2,  // 4: auth.AuthService.SendOTP:input_type -> auth.SendOTPRequest
	3,  // 5: auth.AuthService.VerifyOTP:input_type -> auth.VerifyOTPRequest
	4,  // 6: auth.AuthService.Register:input_type -> auth.RegisterRequest
	5,  // 7: auth.AuthService.CompleteRegistration:input_type -> auth.CompleteRegistrationRequest
	6,  // 8: auth.AuthService.InitiateActivation:input_type -> auth.InitiateActivationRequest
	7,  // 9: auth.AuthService.CompleteActivation:input_type -> auth.CompleteActivationRequest
	8,  // 10: auth.AuthService.RefreshToken:input_type -> auth.RefreshTokenRequest
	9,  // 11: auth.AuthService.Logout:input_type -> auth.LogoutRequest
	10, // 12: auth.AuthService.CheckPhone:output_type -> auth.CheckPhoneResponse
	11, // 13: auth.AuthService.Login:output_type -> auth.LoginResponse
	13, // 14: auth.AuthService.SendOTP:output_type -> auth.StandardResponse
	13, // 15: auth.AuthService.VerifyOTP:output_type -> auth.StandardResponse
	13, // 16: auth.AuthService.Register:output_type -> auth.StandardResponse
	11, // 17: auth.AuthService.CompleteRegistration:output_type -> auth.LoginResponse
	13, // 18: auth.AuthService.InitiateActivation:output_type -> auth.StandardResponse
	13, // 19: auth.AuthService.CompleteActivation:output_type -> auth.StandardResponse
	12, // 20: auth.AuthService.RefreshToken:output_type -> auth.RefreshTokenResponse
	13, // 21: auth.AuthService.Logout:output_type -> auth.StandardResponse
	12, // [12:22] is the sub-list for method output_type
	2,  // [2:12] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_auth_auth_proto_init() }
func file_auth_auth_proto_init() {
	if File_auth_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_auth_proto_rawDesc), len(file_auth_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_auth_proto_goTypes,
		DependencyIndexes: file_auth_auth_proto_depIdxs,
		MessageInfos:      file_auth_auth_proto_msgTypes,
	}.Build()
	File_auth_auth_proto = out.File
	file_auth_auth_proto_goTypes = nil
	file_auth_auth_proto_depIdxs = nil
}
